### ISSUE TITLE
Change params min for InvertedPendulum2-1-9 is not valid

### ISSUE THREAD

**Issue by AdilZouitine** [akimotolab/M2TD3#1]
Hey, 
I've noticed a mistake for `InvertedPendulum2-1-9.yaml`. The `change_param_min` and `change_param_max` are equals (https://github.com/akimotolab/M2TD3/blob/main/configs/environment/InvertedPendulumv2-1_9.yaml#L6).
So this configuration, the environment parameters are the statics. Please let me know if you used this config for your paper experiments or if this mistake is only on the public implementation. 

Best, 
Adil

**Comment by yoshinobc** [comment]
Thanks for the question.

This file (https://github.com/akimotolab/M2TD3/blob/main/configs/environment/InvertedPendulumv2-1_9.yaml) is a file I forgot to delete that I used in an experiment that is not on the paper.
I used this file (https://github.com/akimotolab/M2TD3/blob/main/configs/environment/InvertedPendulumv2-1_31.yaml) for the InvertedPendulum 1 scenario in the paper.

**Comment by AdilZouitine** [comment]
Perfect, thank you 😄 
We met each other @Neurips 2022; thank you for your poster.
