### ISSUE TITLE
Performance reported in Table 1

### ISSUE THREAD

**Issue by AdilZouitine** [akimotolab/M2TD3#2]
Hi, 
Thank you for the implementation.
We met at the poster session at NeurIPS 😄 

The performance for Hopper in Table 1 is low for each method. Is it a typo error? Or is just the gap between mean performance and worst performance huge?
Same as in Figure 3? 

Best

**Comment by yoshinobc** [comment]
The reason for the low performance metrics for all methods in the Hopper environment in Table 1 is not typographical error. Note that Table 1 shows the worst-case performance for the uncertainty parameter space, not the average performance for it. The reason for the low performance in the Hopper environment in Table 1 is that the uncertainty parameter space used in this Hopper environment experiment (Table 4) contains parameters that cannot be solved. In fact, Figure 4 and Figure 5 (c) Hopper 2 in supplementary material show that all methods have lower performance when world friction is 3.0.
